apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
<<<<<<< HEAD
      - image: result
        imagePullPolicy: Never
=======
      - image: SCAGroup6/examplevotingapp_result
>>>>>>> 88653ebfca8783bdcffe492fbfb9d27dc614a762
        name: result
        ports:
        - containerPort: 80
          name: result
