apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
<<<<<<< HEAD
      - image: worker
        imagePullPolicy: Never
=======
      - image: SCAGroup6/examplevotingapp_worker
>>>>>>> 88653ebfca8783bdcffe492fbfb9d27dc614a762
        name: worker
